# Generated by Django 4.2.5 on 2023-12-18 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socialMedia', models.CharField(max_length=15)),
                ('postDate', models.DateField()),
                ('postText', models.CharField(max_length=500)),
                ('postFile', models.FileField(default='', upload_to='media/files')),
                ('postType', models.CharField(max_length=10)),
            ],
        ),
    ]
