# Generated by Django 4.2.5 on 2023-12-18 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='postDate',
        ),
        migrations.AddField(
            model_name='posts',
            name='postDay',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='postMonth',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='posts',
            name='postYear',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
