# Generated by Django 4.2.5 on 2023-12-18 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_posts_postdate_posts_postday_posts_postmonth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ideas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideaTitle', models.CharField(max_length=50)),
                ('ideaText', models.CharField(max_length=1000)),
            ],
        ),
    ]
